### ISSUE TITLE
FATAL ERROR: unexpected end of genotype vector in VCF

### ISSUE THREAD

**Issue by AliceIob** [ruidlpm/pathPhynder#1]
Hi, 

I am trying to use pathPhynder and I am stuck at the very first step. 
I run "Assign informative SNPs to tree branches" : 

`phynder -B -o out_branches.snp mytree.nwk myvcf.vcf.gz`
 and I get this error: 
`FATAL ERROR: unexpected end of genotype vector in VCF sample 0 site 56`

I made an attempt of removing the 56th position from my vcf (entire line) and I get again the exact same error (sample 0 site 56).

Do you have any idea how to fix this? 

Thank you

**Comment by ruidlpm** [comment]
Hello,

Do you have haploid data? Could you send me the first 100 lines of your vcf
so that I can try to identify the problem?

Best,
Rui

**Comment by AliceIob** [comment]
Hi, 

No, my data is diploid and it is filtered for maximum 10% missing information. 

Here the first 100 sites. 

Thanks !
[head100.vcf.txt](https://github.com/ruidlpm/pathPhynder/files/7779981/head100.vcf.txt)

**Comment by ruidlpm** [comment]
Hello Alice,

Unfortunately, pathphynder only works with haploid data.

Best wishes,
Rui
