### ISSUE TITLE
issues for pathPhynder

### ISSUE THREAD

**Issue by zhangjsyeah** [ruidlpm/pathPhynder#3]
dear professors,
I used the example (BigTree_Y) you provided to run pathPhynder and found an error, I would like to know why it stops, thanks for your help

(base) [zhangjs@m1 BigTree_Y]$ pathPhynder -s prepare -i bigtree_annotated_V1.nwk -p teat -f bigtree_branches.snp 

 Program: pathPhynder
 Version: 1.a
 Contact: ruidlpm@gmail.com

	Parameters:

	Best path mode
	--input_tree  bigtree_annotated_V1.nwk
	--prefix  teat
Preparing files for running pathPhynder

**Comment by ruidlpm** [comment]
Hello,

could you please send me an email, providing all the commands you used before and the full output so that I can diagnose the problem?

Thanks

Rui

**Comment by zhangjsyeah** [comment]
我已经收到你的邮件会尽快回复你。i have already received your e-mails.I'm very get back to you .
