### ISSUE TITLE
OK to add to bioconda?

### ISSUE THREAD

**Issue by jfy133** [ruidlpm/pathPhynder#5]
Hi @ruidlpm 

I was asked if I could put pathPhynder onto bioconda for easy installation etc.

I was wondering if you would be OK with me doing this?

A couple of weeks ago, with his permission, I was able to get Richard's phynder onto bioconda (the hard part), so I can carry onto pathPhynder now - if that's Ok with you!

**Comment by ruidlpm** [comment]
Hi James,

of course, thank you. You can try, but I am not sure if it will be easy.
Let me know if I can help
Thanks
Rui

**Comment by jfy133** [comment]
Hehe, OK good to know, we will see! It doesn't look _too_ bad from your instructions 

But otherwise will do (might take a few weeks due to other obligations)!

**Comment by jfy133** [comment]
Hi @ruidlpm finally have a little time to work on this (sorry about that!) - is there any chance you could make a proper v1 GitHub release or tag?

We need a stable tarball for bioconda to pull before 'complication' of the package, and it seems currently you only have a v0.1 tag/(pre)release

**Comment by jfy133** [comment]
So here is the draft bioconda PR, once we have the tarball then I can update the URL and we are pretty much good to go :)

https://github.com/bioconda/bioconda-recipes/pull/48550

Note at the suggestion of someone else on bioconda, they recommended adding the Rscript shebang to the `pathPhynder.R` so an alias is not needed so I patched this in the recipe. Might be worth for you to also do so here (but it is just a suggestion, you may have a reason to use the bash alias, of course)

**Comment by jfy133** [comment]
and we are all in :D
