### ISSUE TITLE
Fatal error: cannot open file 'R/prep_files.R': No such file or directory

### ISSUE THREAD

**Issue by theHatIsBack** [ruidlpm/pathPhynder#6]
I encountered an interesting problem while attempting to use your tool and was hoping you might be able to help me resolve it.

Versions:
> pathPhynder - 1.a
> 
> R - 4.3.2:
> - optparse_1.7.4
> - scales_1.3.0   
> - phytools_2.1-1
> 
> Python - 3.11.7
> 
> macOS 14.1
> 
> Chip - M3 Pro

Command:
` pathPhynder -s prepare -i /Users/cameronferguson/Documents/PhD/y_pestis/tree_building/11th_tree_run/y_pestis_above_5x_with_outgroup/filters_with_0.33_missingness/after_removing_homoplasys/after_removing_homoplasys.nwk -p Users/cameronferguson/Documents/PhD/y_pestis/tree_building/placing_genomes_in_tree/phynder_output/phynder_output_prepare -f /Users/cameronferguson/Documents/PhD/y_pestis/tree_building/placing_genomes_in_tree/phynder_output/branches.snp -r /Users/cameronferguson/Documents/PhD/y_pestis/tree_building/placing_genomes_in_tree/ref/SNP_aln_ref.fasta`

Error message:

> bash: line 2: type: pathPhynder: not found
> Warning message:
> In system("bash -l", input = c("shopt -s expand_aliases", "type pathPhynder"),  :
>   running command '< '/var/folders/xm/zb953_j90vvbpn8l5_jsd4_w0000gn/T//Rtmp1QfzlJ/file4bb47e5713fa' bash -l' had status 1
> 
>  Program: pathPhynder
>  Version: 1.a
>  Contact: ruidlpm@gmail.com
> 
> 	Parameters:
> 
> 	Best path mode
> 	--input_tree  /Users/cameronferguson/Documents/PhD/y_pestis/tree_building/11th_tree_run/y_pestis_above_5x_with_outgroup/filters_with_0.33_missingness/after_removing_homoplasys/after_removing_homoplasys.nwk
> 	--prefix  Users/cameronferguson/Documents/PhD/y_pestis/tree_building/placing_genomes_in_tree/phynder_output/phynder_output_prepare
> Preparing files for running pathPhynder
> Fatal error: cannot open file 'R/prep_files.R': No such file or directory

What's quite interesting is that I've checked the R folder within the pathPhynder directory, and this file is definitely present. I would appreciate any guidance you might have for resolving this issue. Thanks in advance.

**Comment by ruidlpm** [comment]
very sorry for the late reply. Please try reinstallation using conda. The instructions are on the main page. Hopefully that fixes it but let me know if not,.
