### ISSUE TITLE
call_bases_chrY_v2.1.py，error run

### ISSUE THREAD

**Issue by xiaolingLIANG** [ruidlpm/pathPhynder#9]
Processing  intree_folder/Rrox58.bam.pileup
Traceback (most recent call last):
  File "/work/home/sunny717/pathphynder/pathPhynder/inst/python/call_bases_chrY_v2.1.py", line 254, in <module>
    if eval(Ancestral_match + '_count')>0 and eval(Derived_match + '_count')>0:
  File "<string>", line 1
    *_count
    ^
SyntaxError: invalid syntax
Error: intree_folder/Rrox58.bam.intree.txt - does this file exist?
Execution halted

**Comment by ruidlpm** [comment]
I can try to fix this issue if you send me the bam file and the command you used via email.

**Comment by xiaolingLIANG** [comment]
thank you so much ! I've been stuck on this error for several days. I would be incredibly grateful if you could help me resolve it!

**Comment by xiaolingLIANG** [comment]
Hello, thank you for your response.


this is the code i used:
##step1
pathPhynder -s prepare -i /work/home/sunny717/Rr_present/60_mito_alignment/60_modern_alignment_outgroup6/sbatch_run2/run2/snp_sites/pathphynder/66alignment_1000b_4.newick -p 66alignment_rename2 -f /work/home/sunny717/Rr_present/60_mito_alignment/60_modern_alignment_outgroup6/sbatch_run2/run2/snp_sites/pathphynder/run4/66alignment_rename2_branches.snp
##step 2
/work/home/sunny717/pathphynder/pathPhynder/pathPhynder.R -s all -i /work/home/sunny717/Rr_present/60_mito_alignment/60_modern_alignment_outgroup6/sbatch_run2/run2/snp_sites/pathphynder/66alignment_1000b_4.newick -p tree_data/66alignment_rename2 -b /work/home/sunny717/ancientDNA/22ancient/1_mito/mito_mapped_bam/MCS43_mappedrmdup_bam_merge_sort.bam -r /work/home/sunny717/Rr_present/60_mito_alignment/60_modern_alignment_outgroup6/sbatch_run2/run2/snp_sites/pathphynder/run4/NC_008218_mitogenome.fasta


After running step 2, I encountered the following error:
################
Processing intree_folder/MCS43_mappedrmdup_bam_merge_sort.bam.pileup
Traceback (most recent call last):
&nbsp; File "/work/home/sunny717/pathphynder/pathPhynder/inst/python/call_bases_chrY_v2.1.py", line 254, in <module&gt;
&nbsp; &nbsp; if eval(Ancestral_match + '_count')&gt;0 and eval(Derived_match + '_count')&gt;0:
&nbsp; File "<string&gt;", line 1
&nbsp; &nbsp; *_count
&nbsp; &nbsp; ^
SyntaxError: invalid syntax
```"

###########
Could you help me identify where the problem is?
Thank you so much !




梁晓玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruidlpm/pathPhynder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruidlpm/pathPhynder] call_bases_chrY_v2.1.py，error run (Issue #9)





 
I can try to fix this issue if you send me the bam file and the command you used via email.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by ruidlpm** [comment]
thanks. 
It could be that the problem is non ATCG nucleotides in your reference genome or vcf, but I am not sure without having a look at the data. For now, can you try removing non ATCG nucleotides from your vcf file used as input with phynder and then rerun the prepare step and the rest of the analysis

**Comment by xiaolingLIANG** [comment]
The reference genome and VCF file both do not contain non-ATCG bases. The reference genome in the FASTA file is named `&gt;NC_008218.1`. Does this have any impact?




梁晓玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruidlpm/pathPhynder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruidlpm/pathPhynder] call_bases_chrY_v2.1.py，error run (Issue #9)





 
thanks.
 It could be that the problem is non ATCG nucleotides in your reference genome or vcf, but I am not sure without having a look at the data. For now, can you try removing non ATCG nucleotides from your vcf file used as input with phynder and then rerun the prepare step and the rest of the analysis

**Comment by ruidlpm** [comment]
Thanks. Please send me the input files via email so that I can identify and fix this problem.

**Comment by ruidlpm** [comment]
It seems you get a syntax error. I wonder if the problem is the python version. Ensure you are using python3. A good solution is to install via conda. If this does not solve the problem, then please send input files.

**Comment by xiaolingLIANG** [comment]
This is the reference genome and VCF file I used.




梁晓玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruidlpm/pathPhynder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruidlpm/pathPhynder] call_bases_chrY_v2.1.py，error run (Issue #9)





 
It seems you get a syntax error. I wonder if the problem is the python version. Ensure you are using python3. A good solution is to install via conda. If this does not solve the problem, then please send input files.

**Comment by xiaolingLIANG** [comment]
python --version
Python 3.8.18







梁晓玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruidlpm/pathPhynder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruidlpm/pathPhynder] call_bases_chrY_v2.1.py，error run (Issue #9)





 
It seems you get a syntax error. I wonder if the problem is the python version. Ensure you are using python3. A good solution is to install via conda. If this does not solve the problem, then please send input files.

**Comment by xiaolingLIANG** [comment]
Could this be the issue? If so, how should I modify the Python script?


"The error you're encountering is due to invalid syntax in the string passed to the eval function. Specifically, the error message SyntaxError: invalid syntax indicates that "*_count" is not a valid Python syntax. This typically occurs when the string provided to eval is not a valid Python expression."




梁晓玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruidlpm/pathPhynder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruidlpm/pathPhynder] call_bases_chrY_v2.1.py，error run (Issue #9)





 
It seems you get a syntax error. I wonder if the problem is the python version. Ensure you are using python3. A good solution is to install via conda. If this does not solve the problem, then please send input files.

**Comment by ruidlpm** [comment]
Thanks for checking the python version, it seems that's not the problem. No need to change the script. If there is a bug I will fix it. But to understand the problem I need your input files. Please send bam, tree, reference genome and vcf to ruidlpm [at] gmail.com

**Comment by ruidlpm** [comment]
The error that you get is because your vcf contains indels. pathPhynder can only handle biallelic SNPs as input.
To filter out indels run something like:
bcftools view -v snps -c1 -m2 -M2 66_alignment_snpsites_rename2_modified.vcf  >  66_alignment_snpsites_rename2_modified.snps.vcf

I will update the code to provide a more informative error.
